This is the directory for housing all of our OpenKIM tests

============================================================

I'm revisiting this, let's see if we can make it better.

----------------------------------------------

Directory Structure

openkimtest
    -bin  - holds pipeline and other scripts
    -docs - holds documentation automatically generated by doxygen once and a while
    -outputs - holds the commandline outputs from pipeline runs
    -results - holds the result xml files from pipeline or -w runs
    -test - holds the test
    -verify - holds results of verifications during pipeline runs (not working yet)


---------------------------------------------------------

As for the tests:

So, the Tests will inherit from the BaseTest, which should be able to do most of
what is required of tests.

In order to write your own tests, just copy the NullTest.py file, rename the
file and the class name as desired, and write the TestResult method.

-----------------------------------------------------

Test Usage:

usage: python NullTest.py [-h] [-v] [-w]
                   [potential] [element]

positional arguments:
  potential         The first argument is the potential
  element           The second argument is the element
  optional arguments    The remaining are optional

optional arguments:
  -h, --help        show this help message and exit
  -v, --verify      runs the verify method
  -w, --write       writes the xml file to the results directory

-------------------------------------------------------------------

TODO:
    X  - XML writing
    X  - argparsing
    X  - simple pipeline
    O  - Make FCC ASAP compatible.  optional argument for number of unit cells,
             so code knows about the requirements of the potential
    O  - unit test the Tests
    O  - implement TestDependencies
    O  - make GPAW potential implementation a little more effecient?
    O  - integrate the old OpenKIM package, DigitalMaterial
    
-------------------------------------------------------------------
TESTS:    
    X  - FCC lattice constants
    X  - BCC lattice constants
    O  - verify forces are gradients
    O  - Figure out equilibrium structure
    O  - Vacancy formation energy
    O  - Vacancy displacement field
    O  - hexagonal lattice constants
    O  - Elastic Moduli
    O  - maybe verify the lattice constants (see that force is zero)
    O  - unit change test.
    O  - change potential parameters, perhaps make a LennardJones potential
    
